meteor/package.js
mongo-collection-instances 0.2.5 was breaking the [collection-helpers package](https://atmospherejs.com/dburles/collection-helpers)
=> fixes conflict with collection-helpers package

Sortable.js
When having existing classes (E), and we're removing the class (A), if another class (B) was added since the removed class (A) was initially added, the names of the previous classes are joined with the new class (E and B) without a separator space.
See http://jsbin.com/nohavapeju/2/edit?html,css,js,output
In IE9.
=> Don't join class names when removing classes after additions.

ng-sortable.js
I suggest retrieving the ngSortable options using a two-way binding in a local scope, instead of using `attrs` and `scope.$eval`.
This would remove the need for the 'ugly if'.
=> Use isolated scope with two-way binding in ng-sortable

Sortable.js
`_closest()` attempts to matching elements, supporting a very limited subset of CSS selectors.  It is clear from the code that support is expected for an option *element name* any number of *class selectors* e.g. `"DIV.foo.bar"`
Assume that `el.className === "foo bar"`
Assume that your selector is `"DIV.foo.bar"`
`(' ' + el.className + ' ').match(re)` will only have one match - `" foo "` - because the `"\\s"` trailing character on `"foo"` prevents `" bar "` from being matched
EZ fix is just to make sure the trailing whitespace is not consumed by the regex
=> Correctly match multiple class names

ng-sortable.js
For some reason, if I attempt to use ng-sortable within a directive of my own, if certain options aren't being watched they won't work.  They do still work in other contexts, like a basic controller/template pair.
Anyway, adding them into the list of properties to watch solves the problem - though honestly I can't explain exactly why that is.
If there's a better way to fix this, cool - this is just what I did locally to get things working as expected.
=> angular watch more options

README.md, Sortable.js, package.json, react-sortable-mixin.js
fix for #411 #250 and #436
as well as #387
and #146 #393
**added forcePolyfill option.**
- forcePolyfill is made to make cross-browser testing more easy.
- forcePolyfill provides a reliable, consistent cross-browser Solution for
Sortable.
- forcePolyfill gives us the possibility to change the way "dragged items"
lok like.
=> fix click event for mobile devices and old browser

Sortable.js
This addresses issue #250 with the fix mentioned by @kirilgorbachov.
I've tested with Chrome and Firefox on Mac and Android and it fixed the issue without causing any problems.
P.S. Pull request #406 has caused a jshint error.
=> Allow click events for touch devices

meteor/README.md, meteor/reactivize.js
Add an option to specify selector in meteor helper. This way you can operate only on a subset of collection.
Otherwise `Sortable` operates on whole collection (everything that is published to client).
=> meteor: option to specify collection selector

meteor/package.js
There was an issue on the collection-extensions package that mongo-collection-instances depends on that was recently patched.
=> Update dependency of mongo-collection-instances

ng-sortable.js
This change allows `ng-sortable.js` to work with Browserify (see closed PR #471). It works on my Angular app that uses Browserify to bundle the JS. To use, just `require('Sortable/ng-sortable');`
=> Added Browserify support for ng-sortable

jquery.binding.js
I have found a bug in the jquery binding. The arguments variable which was used to pass the function arguments to apply(...) is coming from the $.each handler function, and therefore doesn't contain the actual function call arguments.
This patch should fix the bug.
=> Bugfix in jquery.binding.js

react-sortable-mixin.js
Sorry if this fails CI or something..I wrote this in the github editor, since its simple. I can be a more thorough a bit later if you'd like.
react 0.14 deprecates .getDOMNode() so this PR maintains the current default but allows it to be configured, effectively removing the version specific React dependence.
Thanks for the great library!
=> Add `getContainer` option for better react version support

README.md, react-sortable-mixin.js
with React **v0.14** ```this.refs.*.getDOMNode()``` is deprecated,
we have to use ```this.refs.* instead```, to reference the DOM Node.
this is a implementation, that is backward compatible
* misspelled ref in README fixed
* fixed Demo of forceFallback
=> more reliable way to get the DOM Node

README.md, Sortable.html, bower.json
USAGE
```
<link rel="import" href="bower_components/Sortable/Sortable.html">
<sortable-js handle=".handle" draggable="li" group="user">
<template is="dom-repeat" items={{names}}>
<div>{{item}}</div>
</template>
<sortable-js>
```
=> Add Polymer Support

knockout-sortable.js
The items would not swap positions when you dragged item with index 1 to
the top of the stack at index 0.
=> Fix to knockout sorting when dragging item index 1 to 0.

bower.json
Absolutely optional, like angularjs or reactjs.
=> Remove Polymer from bower dependencies

Sortable.js
should fix #618 and #597
oldIndex was changed first by with the item being dragged, but also by the drag event of the parent (which should be avoided when we are not using the drag-handle)
=> avoid changing oldIndex by the parent container

README.md, Sortable.js
An attempt to implement the "distance" option (like http://api.jqueryui.com/sortable/#option-distance).
This is useful when your sortable element is also clickable. This prevents the drag to begin due to a micro-movement when you click.
**this works in fallback mode only**
=> "distance" option

Sortable.js
For instance, say you are sorting tbody's within a table element.  There
can also exist tfoot and thead within the table element.  The _index()
function assumes that the list of elements within the parent is
homogenus (ie: just li's below an ol/ul).  This isnt the case when
sorting tbody under table.  This is edge case until you want to group
tr's under a table and sort on those groupings.
=> fix for sorting elements within a non-homogenus list of elements

ng-sortable.js
Sometimes evt.from is different from evt.item.parentNode because the item has been moved already so using evt.item.nextSibling won't work when doing evt.from.insertBefore, because nextSibling is not a child of evt.from.
So in those cases we use evt.clone.nextSibling instead.
=> Fix for Issue #580 [Angular] Javascript error when moving items between two lists very fast #683

Sortable.js
don't trigger start event when an element is been dragged, otherwise the evt.oldindex always wrong when set options.group.
=> fix bug about evt.oldIndex when set options.group

react-sortable-mixin.js
The current behavior (in `master`) is to define the handling functions for events as strings. Default for `onSort` for example is `handleSort`. Commit 8cef762d11dbabb27e489727bcc8fd5dfe8d844d changed this behavior forcing handling functions to be defined as functions in the options. This breaks all existing code, resulting in a no-op even with the default options (which still define the default handlers as strings).
This commit restores previous behavior AND allows you to define your handlers as functions directly, if you’re so inclined.
=> Allow event functions to be defined as functions AND strings.

knockout-sortable.js
This PR changes the dependency resolution logic of knockout-sortable.js to first look for knockout / Sortable global references, before trying require and AMD. This allows the script to be used in a require / AMD environment but still allowing knockout (and/or Sortable) to be referenced globally.
It can be advantageous, even when in a browserify / requireJS / AMD environment, to include separate scripts to a public CDN for popular libraries, like knockout in order to take advantage of cross-site caching of these libraries. In this case, large dependencies like knockout do not need to increase the size of a generated JS build (in the case of browserify) or cause additional http requests (in the case of AMD / requireJS).
=> knockout-sortable - prioritise global dependencies if available

react-sortable-mixin.js
Fixing error: *Uncaught TypeError: this.getDOMNode is not a function*
=> React Mixin - Fixing check for existence of getDOMNode function

Sortable.js
It is not valid to assume that Sortable's **prototype contains what you expect it to**.
In my environment, Sortable is loaded by `requirejs`, and the **prototype is modified** in requirejs's loader callback by injecting a special `__moduleId__` property into the prototype, in a fashion like this:
```javascript
requirejs.onResourceLoad = function(context, map, depArray) {
context.defined[map.id].prototype.__moduleId__ = map.id;
};
```
At [Sortable.js#L232](https://github.com/RubaXa/Sortable/blob/master/Sortable.js#L232) this effectively leads to trying to call `.bind` on a `String` object, resulting in `this[fn].bind is not a function` error.
There should be a smarter way to copy functions from the prototype, so far I can suggest an extra check for object type before calling `.bind`: …
=> Calling this[fn].bind requires extra check

Sortable.html
Object.assign [is not supported in IE](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign); README includes support for IE. 
Based on my [understanding of Object.assign](http://www.2ality.com/2014/01/object-assign.html), this should be equivalent.
Thanks @gutenye for the Polymer element!
=> Replace Object.assign for IE support

Sortable.html
Currently it is not possible to re-initialize the sortable component after it's been destroyed. I've added a method and wrapped everything in the attached in there and instead I'm calling that method on attached.
Then it'll be possible to call $0.initialize(); on the component to re-enable sortable.
/edit:
Just realized perhaps the same thing should be done with detached and creating a method to destroy it, so did that as well.
=> [Polymer component]Added method to re-initialize sortable

README.md
As mixins are not supported in ES2015 / TypeScript syntax here is example of ES2015 ref based implementation.
Using refs is the preferred (by facebook) "escape hatch" to underlaying DOM nodes: [React: The ref Callback Attribute](https://facebook.github.io/react/docs/more-about-refs.html#the-ref-callback-attribute)
```js
import * as React from "react";
import Sortable from 'sortablejs';
export class SortableExampleEsnext extends React.Component {
sortableContainersDecorator = (componentBackingInstance) => {
// check if backing instance not null
if (componentBackingInstance) {
let options = {
handle: ".group-title" // Restricts sort start click/touch to the specified element
};
Sortable.create(componentBackingInstance, options);
}
};
sortableGroupDecorator = (componentBackingInstance) => { …
```
=> Update README.md: Add Support React ES2015 / TypeScript syntax example

README.md
In the case of `sortable.options.group`, `[object Object]` is returned.
Correctly is seems to `sortable.options.group.name`.
Sorry my bad English. Thanks!
=> Fix incorrect example code

knockout-sortable.js
If `ko.options.deferUpdates = true`, then updates to the UI don't happen immediately when you modify the viewModel. 
For the sortable binding, this means that after removing a moved item, it doesn't recreate it at the new position.
Calling `ko.tasks.runEarly` before re-inserting the item into the observableArray makes KO register the removal.
This is the fix proposed by @adriaanmeuris in RubaXa/Sortable#712
=> knockout: run deferred tasks early

README.md
Adding a comma after the following statement, will make the options section valid javascript.
`fallbackOnBody: false` to `fallbackOnBody: false,`
=> Missing comma on fallbackOnBody and fallbackClass

jquery.binding.js
Hi,
`
$("#list").sortable("widget"); // get Sortable instance
`
from the docs wasn't working.
It's obvious since the used `return` would only return from its `function` and the real returned thing was `this`.
=> jquery.binding: fixed non-working widget method

ng-sortable.js
Now only supports such an case:
```html
<ul ng-sortable>
<li ng-repeat="item in m.items">{{item}}</li>
</ul>
```
This PR added support also for such an case:
```html
<ul ng-sortable>
<li data-ng-repeat="item in m.items">{{item}}</li>
</ul>
```
=> Added support attribute "data-ng-repeat"

Sortable.js
Don't null object links (rootEl, dragEl, etc) on Destroy. There are scenarios where this causes ```Sortable.js:1096 Uncaught TypeError: Cannot read property 'dispatchEvent' of null```. For example, this happens on Angular when you drag items containing sub-Sortables between lists. When you drop an item, it naturally executes onDrop. At the same time it destroys its sub-list (a child Sortable), which also calls onDrop. The latter onDrop resets the links, and that breaks the workflow of the initial onDrop.
=> Fix Destroy workflow

Sortable.js
- don't forget to turn off standard pointerevents for scrolling:
-> touch-action: none;
-> -ms-touch-action: none; //older IE versions
- drawback/known issue : option delay isn't supported in conjunction with ms touch
=> - get Sortable running with IE and touch devices, aka pointerevent support

Sortable.js
With Chrome version 56 the passive capture option in addEventListener defaults to true instead of false which causes dragging on touch devices to simultaneously also scroll.
Tested on Android Chrome, and device mode in Edge, Chrome and Firefox.
=> fix: make drag on touch work in scrollable element

Sortable.js
The current code only checks for `mousedown` event. But there is a binding for `pointerdown` event.
Adding this checking will make sure `pointerdown` event does not pass if it's not triggered with left button.
=> Add checking for pointerdown type

README.md
Fixes #1166 
I removed the cdnjs link since it requires manual updates.
=> Update jsDelivr links and remove old/broken cdnjs link

Sortable.js
This PR changes the _matches() function to use el.matches(), or el.msMatchesSelector() for IE9. The result is more flexible selector support for options such as `filter` and `draggable`, e.g. `.classA:not(.classB)`.
I believe this works with all browsers Sortable supports, but if not I can always add additional prefixed matchesSelector alternatives for older browsers or even fall back to the existing custom function if nothing else is supported.
Fixes #1219
=> Use Element.matches for improved selector support

Sortable.js
How the onChoose event is fired before the sortable-chosen style is added, it should be able to do more fine control
=> Modify the onChoose event firing order

Sortable.js
There are reported issues with the option `delay` not working, specifically on mobile (see GitHub Issues [659], [981], [989], [1130], [1136]).
A `dragStartFn` call loses its context because it is invoked by `setTimeout`.
Bind the context.
I do not believe this is necessary for other `setTimeout` or `setInterval` calls because they meet one of the following criteria:
1. Their function calls do not require a context.
2. The correct context is already in scope by the variable `_this`.
3. Private functions already have their context bounded to them.
[659]: https://github.com/RubaXa/Sortable/issues/659
[981]: https://github.com/RubaXa/Sortable/issues/981
[989]: https://github.com/RubaXa/Sortable/issues/989
[1130]: https://github.com/RubaXa/Sortable/issues/1130
[1136]: …
=> (fix) Bind context to setTimeout

README.md, Sortable.js
In short, this revamp allows for elements that are parents of the currently hovered element to also autoscroll.
For native DnD, it autoscrolls the parents, but does not autoscroll the hovered element, as this is handled by HTML5.
Working demo is available here: https://jsbin.com/kesewor/edit?html,js,output
This should solve issue #1373
=> Autoscroll revamp

Sortable.js
Delayed dragging not work correctly into Ios and Android (with `forceFallback`).
In `Ios` prob with `TouchEvent.clientX`, need use `TouchEvent.touches[0].clientX`.
`Android` on start dragging instead `touchmove` send event `mousemove`.
This commit fix it.
=> Fix delayed dragging in Ios and Android

Sortable.js
Currently the auto scroll code does not check if the overflowing parent is a scrolling container. This fix addresses the issue.
=> Fix Issue where an overflowing parent is scrolled but it has overflow: hidden

Sortable.js
Only install these events on `document` while `dragEl` is actually set, since the callback doesn't do anything otherwise anyway. This prevents these callbacks from showing up in performance profiles where they looks like they occupy the CPU at high rates while not actually doing anything.
=> Optimize nearestEmptyInsertDetectEvent callback

README.md, Sortable.js
We're creating a sort of Kanban in our project where the requirements dont allow for drag handles. 
Added a new config option that allows you to apply a delay only if the event was a touchevent
=> Add option to only apply delay on touch events

README.md
from 2.0+ Angular is not .js anymore, it is more correct to call it just Angular
=> rename angularjs to angular

src/Sortable.js
As mentioned in #1644 (and demoed here: https://jsfiddle.net/4kcbzLse/) there is a `transform: translateZ(0)` added when an item is first dragged, but this is not then removed when an item is dropped. This can cause any extruding child elements (such as tooltips) to be overlapped by adjacent content.
When an item is dropped, the now vestigial `transform: translateZ(0)` is removed, rather than simply left.
=> Remove transforms after drop to prevent overlap of adjacent children

src/Sortable.js
I find if the `destory` method called before `_dragStartTimer` trigger, the events linsted by `ownerDocument` will not disabled.
https://jsbin.com/sezupey/edit?html,css,js,output
Could we use this pr fix?
=> disable delayed drag events during destory

src/utils.js
When I use Chrome 41, got a lot of error of 'TypeError: Cannot read property getBoundingClientRect of undefined'.Because in 'utils.js' 'getWindowScrollingElement' function, Chrome < 44 FF < 47 not support scrollingElement too.
=> Fix(utils): Chrome < 44 not support scrollingElement

README.md
As requested in https://github.com/SortableJS/Sortable/issues/1763
=> Fixed a typo in the description of the 'closest' method

src/Sortable.js
That solves an issue with nested sortables.
example of error https://jsbin.com/xabonox/edit?html,css,js
An error appears when all following conditions are met:
1)You have two nested sortable containers
2)option “pull:clone” i set at least on the parent container
3)You drag an item from the parent container into the nested container
The item is moved but not cloned and you get the error: 
“Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted”
=> Solves "insert Before error" issue on nested lists

src/Animation.js
=> Not tree-shake repaint function by compressors like terser

README.md
The doc was missing the case of keeping the default insertion point based on the direction.
closes #1861
=> Fix the doc about the onMove return values

composer.json
After merging this PR, the `RubaXa/Sortable` repo can be submitted to Packagist.org under the `RubaXa` org. Clean and simple no more maintaining of [forks](https://github.com/components/Sortable). Hooray!
=> Support Composer package manager

packages/sortable/src/PluginManager.ts
closes #1581
@beljand Thank you making these changes.
We had a repo refactor and it broke your PR so I made the PR. All credit to you!  :)
=> fix(plugins): ignore mounting duplicate plugins

README.md
Hi,
The emptyInsertThreshold is not really needed (at least in recent browsers), as the function can be obtained by a pure css solution.
I propose this in the README - of course you're free to rewrite it and/or put it somewhere else.
Other ideas :
- Managing automatically an "empty" class when the list is empty (not relying on the :empty which works only if there's no node at all, even text ones)
- Have an "emptyPadding" option, adding automatically padding on an empty list. Note that the required padding can be bottom and/or right, or even top and/or left
=> Trick for emptyInsertThreshold

src/Sortable.js
When dragging an element to the end of the list, and existing non draggable elements at the end of the list.  Appending it to the end of the list is not incorrect, It should be inserted before the next sibling of the last draggable element.
=> fix the drag position problem when existing non draggable elements at the end of the list

src/Sortable.js
Android Chrome will not trigger a click event if a user drags an item,
even if the item is dropped back into its original placement. This
means that whenever the "ignore next click" handling is activated, the
user's _next_ click (unrelated to dragging) will be ignored.
This commit solves this by never activating the "ignore next click"
handling on Android Chrome.
=> Prevent ignored touches on Android Chrome.

README.md
For code blocks on github there is a button that lets you copy the input. Before it would include the dollar sign which would not work in the terminal
example before:
$ npm install sortablejs --save
after:
npm install sortablejs --save
=> docs: remove dollar sign from code blocks

plugins/AutoScroll/README.md
Corrects one instance in which the property is written with a lowercase "s"
=> docs: properly capitalize forceAutoScrollFallback option

src/Sortable.js
See https://github.com/SortableJS/Sortable/issues/2346 for explanation and code samples of the issue.
When sortable elements contain web components with shadowRoot, and forceFallback is enabled, swapping elements is not working correctly.
DOM Example:
```
<ul id="list" class="list-group">
<li class="list-group-item"><custom-handle></custom-handle><custom-content></custom-content></li>
<li class="list-group-item"><custom-handle></custom-handle><custom-content></custom-content></li>
</li>
```
=> fix: set the target as the host element when target contains a shadowRoot

src/utils.js
When an element that is a (light DOM) child of a shadow DOM element triggers an event (e.g., a click event), `getParentOrHost` checks for the parent shadow DOM's host (which refers to itself) causing [the do..while loop in `closest`](https://github.com/SortableJS/Sortable/blob/master/src/utils.js#L50-L65) to be called infinitely. 
This leads to the browser tab/window being frozen.
The solution is to check if the element passed to getParentOrHost has a host property that refers to itself.
=> Fix: Sortable Freezes Browser (Shadow DOM)
