SortableJS/Sortable

- Sortable.js
> fix index calculation to skip templates

- ng-sortable.js
In relation to https://github.com/RubaXa/Sortable/issues/237
> Deep copy object to avoid unwanted referencing

- Sortable.js
Related to https://github.com/RubaXa/Sortable/pull/312
> Add delay between touchstart and dragstart

- README.md
Just a small typo fix on README.md for documentation.
> Fixed small typo on documentation

- ng-sortable.js
- st/app.js
> ng-sortable: support configuration constant

- ng-sortable.js
> ng-sortable: add prefix to version constant

- Sortable.js
I think u do not need to build a polyfill for Function.bind since u had used the Array.prototype.forEach of apis in es5,the support check is not necessary.
> remove bind polyfill

- react-sortable-mixin.js
Apologies for breaking jshint in #406... I didn't run grunt before committing.
> Fix jshint

- Sortable.js
_emulateDragOver optimized to reduce the interval tics without reducing performance. 
That provides a fluidity similar to the native drag and drop mode.
> improves the fallback mode fluidity

- Sortable.js
> fix fallback moves in owner container

- Sortable.js
drag/drop handlers should be disabled in forceFallback mode to avoid unwanted behaviors when dragging elements
>  remove drag/drop handlers in forceFallback mode

- CONTRIBUTING.md
First time using grunt instead of gulp, so I added some setup steps to CONTRIBUTING.md
> Added some Setup steps

- Sortable.js
Fix #532 and works on IE9/10.
http://caniuse.com/#feat=pointer-events
via https://github.com/timruffles/ios-html5-drag-drop-shim/pull/47
> Support iOS 8.4.1 and safety IE9/10

- react-sortable-mixin.js
Only components having a state are currently working correctly with the sortable mixing. The proposed fix is to allow custom state handling method to be passed in as config.
> Allow a custom setState handler on the using component

- knockout-sortable.js
fixes the following issue
https://github.com/RubaXa/Sortable/issues/638
> add Sortable as dependency for knockout-sortable

- README.md
ref={i} for  https://facebook.github.io/react/docs/multiple-components.html#dynamic-children
> few errors thrown by react0.14

- knockout-sortable.js
some of the comments were really long so i broke them up into shorter lines
> format comments

- ng-sortable.js
Make access to all DOM info available by the library.
> #666 Return DOM information of element in env object

- ng-sortable.js
need using `draggable` option to restrict only ng-repeat elements
demo is base on example in #373 :
https://jsbin.com/famugi/edit?html,js,output
> small fix with #373

- CONTRIBUTING.md
- Sortable.js
fix bug https://github.com/RubaXa/Sortable/issues/628 and formatting code for meet style
> new PR for https://github.com/RubaXa/Sortable/pull/741

- Sortable.js
> trigger most specialized events first

- README.md
Quick fix on the example in the readme.
> Fixed Polymer example.

- ng-sortable.js
setData is not triggered on isolated scopes http://jsbin.com/yimununobo/1/edit?js,console,output
> Include setData option on angular watchers

- ng-sortable.js
The PR allows the angular directive to work when debug annotations are not switched on. Fixes #865
> Enable the angular directive to work when debugInfo is off

- README.md
- Sortable.html
This pull request is a work in progress because it's more of a question if this is a feature you want to add to the component.
In my case I want to change the order and then update a ordering property on my objects in the list.
Using the polymer splice functions will trigger a change with a changeRecord which in turn will propagate to the rest-api component which sends multiple DELETE and POST request to the server when the only thing i want to do is send the appropriate PATCH requests to update my ordering value.
My change below updates the internal list and enables me to update my property on update events and then notify polymer of the change.
This feature might be good to add under a flag? Or is this something not relevant to the component?
> Manually handle updates

- README.md
- Sortable.js
This PR is an attempt to solve issue #833 by introducing new option: scrollFn.
> Custom autoscrolling function

- Sortable.html
- Sortable.js
There were still some lingering changes after merging #630. Mostly incorrect values of `this` (pointing to `window` instead of the Polymer element) and some function references.
> Fix compilation on ES5 for Polymer

- Sortable.js
> Revert "Fix Destroy workflow"

- README.md
> [Fix] missing semicolon in README

- Sortable.js
We should cancel dnd if original target is content editable, because of dnd broken content editable 😵
> cancel dnd if original target is content editable

- README.md
fixes issue #1243
"cannot drag elements in Cordova iOS app"
https://github.com/RubaXa/Sortable/issues/1243
> fixes issue #1243

- README.md
- Sortable.js
> Add old _index functionality

- src/Sortable.js
[ FIX BUG ] fix error in angular server side render
> fix: error in angular server side render

- src/Sortable.js
Looks like a typo. No such function this._animate. The function should be this.animate.
> Undefined function _animate in _showClone

- src/utils.js
> add MSCSSMatrix to matrixFn options

- st/app.js
> Minor fix for IE compatibility in st/app.js UI of thresholds demo

- src/Sortable.js
> Fix clicking select tag 

- README.md
Readme invalid hyperlinks corrected Fixes #1918
> Readme invalid hyperlinks corrected

- lerna.json
- packages/sortable/package.json
- packages/utils/src/utils.ts
> fix: (IE11 "SCRIPT16389)

- Sortable.js
Added fix for following issue:
https://github.com/SortableJS/Vue.Draggable/issues/1199
> Added conditional statement whether dragged element should be dropped
